### ISSUE TITLE
Namespace Management

### ISSUE THREAD

**Issue by mnkg561** [keikoproj/manager#4]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
We need to support the following functionality as part of Namespace Management
1. Allow users to configure steps involved in Namespace Creation.
2. Must allow options to choose applicable clusters

**What you expected to happen**:
1. Users should be able to design namespace creation template based on environment, cluster and cloud.
2. New namespace creation should create the namespace based on the template it is referenced to.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

```
- controller logs:
```
$ kubectl logs <manager>
```

**Comment by wanghong230** [comment]
Should we keep using the Argo workflow?

**Comment by mnkg561** [comment]
ManagedNamespace provides following in high level
clusterName
params:
templateName:
NamespaceResources
Namespace
Resources
- Name
Type
DependsOn:
CreateOnly
OneOf{
ServiceAccount
Role
RoleBinding
ResourceQuota
}
- Name
Type
DependsOn:
CreateOnly
OneOf{
ServiceAccount
Role
RoleBinding
ResourceQuota
}
clusterName: Name of the cluster in which this namespace needs to be created
params: map[string]string - this should be used to provide the runtime values for the exportedParams for the namespace template

templateName: Name of the namespace template to be used for this and namespace template must exists. Optional

NamespaceResources: Additional resources to be created in addition to the template provided and can also be used to create namespace directly without using template.

**Comment by mnkg561** [comment]
Sample Template:

```
apiVersion: manager.keikoproj.io/v1alpha1
kind: ManagedNamespace
metadata:
  name: second-namespace
  namespace: docker-desktop
spec:
  clusterName: docker-desktop
  params:
    env: "preprod"
    registry: "docker.io"
    name: "second-namespace"
  templateName: namespacetemplate-sample
```
